// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightSensorService.proto

package com.akpan.light;

public interface LightControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.akpan.light.LightControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command = 1;</code>
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();
}
