// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightSensorService.proto

package com.akpan.light;

public interface LightControlDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.akpan.light.LightControlData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool light_status = 1;</code>
   */
  boolean getLightStatus();

  /**
   * <code>string time_of_day = 2;</code>
   */
  java.lang.String getTimeOfDay();
  /**
   * <code>string time_of_day = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimeOfDayBytes();
}
