// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightSensorService.proto

package com.akpan.light;

public final class LightSensorServiceProto {
  private LightSensorServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_akpan_light_LightControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_akpan_light_LightControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_akpan_light_LightControlData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_akpan_light_LightControlData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030LightSensorService.proto\022\017com.akpan.li" +
      "ght\"&\n\023LightControlRequest\022\017\n\007command\030\001 " +
      "\001(\t\"=\n\020LightControlData\022\024\n\014light_status\030" +
      "\001 \001(\010\022\023\n\013time_of_day\030\002 \001(\t2u\n\023LightContr" +
      "olService\022^\n\021StreamTemperature\022$.com.akp" +
      "an.light.LightControlRequest\032!.com.akpan" +
      ".light.LightControlData0\001B,\n\017com.akpan.l" +
      "ightB\027LightSensorServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_akpan_light_LightControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_akpan_light_LightControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_akpan_light_LightControlRequest_descriptor,
        new java.lang.String[] { "Command", });
    internal_static_com_akpan_light_LightControlData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_akpan_light_LightControlData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_akpan_light_LightControlData_descriptor,
        new java.lang.String[] { "LightStatus", "TimeOfDay", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
