// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightSensorService.proto

package com.akpan.light;

public interface ToggleLightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.akpan.light.ToggleLightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool toggle_on = 1;</code>
   */
  boolean getToggleOn();
}
