// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureSensorService.proto

package com.akpan.temperature;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.akpan.temperature.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {
}
