// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureSensorService.proto

package com.akpan.temperature;

public interface TemperatureDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.akpan.temperature.TemperatureData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_id = 1;</code>
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensor_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();

  /**
   * <code>double temperature = 2;</code>
   */
  double getTemperature();

  /**
   * <code>string timestamp = 3;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
